title: "Alejandro Morillas"
description: "Porfolio de Alejandro Morillas, Analista de Datos Junior orientado a transformar datos en información útil para la toma de decisiones."
theme: minima

url: "https://alejandromtdata.github.io"
baseurl: "/website_data"
lang: es

author: "Alejandro Morillas"
email: "alejandromtdata@outlook.es"

github_username: alejandromtdata
plugins:
  - jekyll-feed

minima:
  date_format: "%d/%m/%Y"

header_pages:
  - index.md
  - about.md
  - tecnologies.md
  - projects.md

